version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - ./user_service/db:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - messenger

  user_service:
    build: ./user_service
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - messenger
  
  chat_service:
    build: ./chat_service
    ports:
      - "8001:8001"
    depends_on:
      - user_service
    networks:
      - messenger
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./chat_service/db_init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - messenger
      
volumes:
  mongodb_data:
  redis_data:

networks:
  messenger:   